import { PrismaClient } from "@prisma/client";
import { PrismaBetterSqlite3 } from "@prisma/adapter-better-sqlite3";
import path from "path";

const dbUrl = "file:" + path.resolve(process.cwd(), "dev.db").replace(/\\/g, "/");

const prisma = new PrismaClient({
  adapter: new PrismaBetterSqlite3({ url: dbUrl }),
});

async function main() {
  console.log("Seeding database...");

  await prisma.disease.deleteMany();
  await prisma.distribution.deleteMany();
  await prisma.careGuide.deleteMany();
  await prisma.plant.deleteMany();

  const plants = [
    {
      name: "Monstera",
      scientificName: "Monstera deliciosa",
      genus: "Monstera",
      family: "Araceae",
      kingdom: "Plantae",
      description:
        "Monstera deliciosa, dikenal sebagai 'Janda Bolong' atau 'Swiss Cheese Plant', adalah tanaman tropis dari hutan hujan Amerika Tengah.",
      imageUrl: "/images/monstera.jpg",
      careGuide: {
        watering: "Siram 1-2 kali seminggu, biarkan tanah mengering.",
        sunlight: "Cahaya terang tidak langsung.",
        temperature: "18-30°C.",
        soil: "Media tanam gembur, kaya organik, drainase baik.",
        fertilizer: "Pupuk cair seimbang setiap 2-4 minggu.",
        humidity: "Kelembaban tinggi (60-80%).",
        toxicity: "Beracun bagi hewan peliharaan.",
        pruning: "Pangkas daun menguning.",
        repotting: "Setiap 1-2 tahun.",
        difficulty: "Mudah",
      },
      distributions: [
        { region: "Chiapas", country: "Mexico", latitude: 16.5, longitude: -92.5, type: "native" },
        { region: "Guatemala", country: "Guatemala", latitude: 15.78, longitude: -90.23, type: "native" },
        { region: "Indonesia", country: "Indonesia", latitude: -0.79, longitude: 113.92, type: "introduced" },
      ],
      diseases: [
        {
          name: "Busuk Akar",
          scientificName: "Pythium spp.",
          symptoms: "Daun menguning, layu, akar coklat.",
          cause: "Overwatering.",
          treatment: "Kurangi penyiraman, potong akar busuk.",
          prevention: "Drainase baik.",
        },
      ],
    },
    {
      name: "Lidah Mertua",
      scientificName: "Sansevieria trifasciata",
      genus: "Sansevieria",
      family: "Asparagaceae",
      kingdom: "Plantae",
      description:
        "Sansevieria trifasciata atau Lidah Mertua adalah tanaman hias populer yang sangat mudah dirawat.",
      imageUrl: "/images/sansevieria.jpg",
      careGuide: {
        watering: "Siram hanya saat tanah benar-benar kering, setiap 2-4 minggu.",
        sunlight: "Toleran berbagai kondisi cahaya.",
        temperature: "15-30°C.",
        soil: "Media tanam cepat kering.",
        fertilizer: "Pupuk kaktus cair setiap 3-4 bulan.",
        humidity: "Toleran kelembaban rendah.",
        toxicity: "Beracun bagi hewan.",
        pruning: "Potong daun rusak.",
        repotting: "Setiap 2-3 tahun.",
        difficulty: "Sangat Mudah",
      },
      distributions: [
        { region: "Nigeria", country: "Nigeria", latitude: 9.08, longitude: 8.68, type: "native" },
        { region: "Kenya", country: "Kenya", latitude: -0.02, longitude: 37.91, type: "native" },
        { region: "Indonesia", country: "Indonesia", latitude: -2.55, longitude: 118.0, type: "introduced" },
      ],
      diseases: [
        {
          name: "Busuk Daun",
          scientificName: "Erwinia carotovora",
          symptoms: "Daun lembek, berair.",
          cause: "Overwatering.",
          treatment: "Potong bagian busuk.",
          prevention: "Jangan terlalu sering menyiram.",
        },
      ],
    },
    {
      name: "Karet Kebo",
      scientificName: "Ficus elastica",
      genus: "Ficus",
      family: "Moraceae",
      kingdom: "Plantae",
      description:
        "Ficus elastica atau Karet Kebo adalah tanaman hias daun dengan daun lebar mengkilap.",
      imageUrl: "/images/ficus.jpg",
      careGuide: {
        watering: "Siram saat lapisan atas tanah mengering.",
        sunlight: "Cahaya terang tidak langsung.",
        temperature: "16-27°C.",
        soil: "Media tanam subur, gembur.",
        fertilizer: "Pupuk cair setiap bulan.",
        humidity: "Kelembaban sedang hingga tinggi.",
        toxicity: "Beracun jika tertelan.",
        pruning: "Pangkas batang atas.",
        repotting: "1-2 tahun untuk tanaman muda.",
        difficulty: "Mudah",
      },
      distributions: [
        { region: "Sumatera", country: "Indonesia", latitude: -0.59, longitude: 101.34, type: "native" },
        { region: "Jawa", country: "Indonesia", latitude: -7.26, longitude: 110.0, type: "native" },
        { region: "India Timur", country: "India", latitude: 22.99, longitude: 87.85, type: "native" },
      ],
      diseases: [
        {
          name: "Bercak Daun",
          scientificName: "Cercospora spp.",
          symptoms: "Bercak coklat pada daun.",
          cause: "Infeksi jamur.",
          treatment: "Potong daun, semprot fungisida.",
          prevention: "Jaga sirkulasi udara.",
        },
      ],
    },
    {
      name: "Lidah Buaya",
      scientificName: "Aloe vera",
      genus: "Aloe",
      family: "Asphodelaceae",
      kingdom: "Plantae",
      description:
        "Aloe vera atau Lidah Buaya adalah tanaman sukulen yang terkenal dengan manfaatnya untuk kesehatan kulit.",
      imageUrl: "/images/aloe.jpg",
      careGuide: {
        watering: "Siram setiap 2-3 minggu.",
        sunlight: "Cahaya terang hingga sinar langsung.",
        temperature: "16-30°C.",
        soil: "Media tanam kaktus.",
        fertilizer: "Pupuk kaktus setiap bulan saat musim tanam.",
        humidity: "Toleran kelembaban rendah.",
        toxicity: "Beracun bagi hewan.",
        pruning: "Potong daun luar tua.",
        repotting: "Saat anakan muncul.",
        difficulty: "Sangat Mudah",
      },
      distributions: [
        { region: "Yaman", country: "Yaman", latitude: 15.55, longitude: 48.52, type: "native" },
        { region: "Maroko", country: "Maroko", latitude: 31.79, longitude: -7.09, type: "native" },
        { region: "Indonesia", country: "Indonesia", latitude: -5.0, longitude: 120.0, type: "introduced" },
      ],
      diseases: [
        {
          name: "Busuk Akar",
          scientificName: "Phytophthora spp.",
          symptoms: "Daun menguning, lembek.",
          cause: "Overwatering.",
          treatment: "Hentikan penyiraman, potong busuk.",
          prevention: "Drainase baik.",
        },
      ],
    },
    {
      name: "Mawar",
      scientificName: "Rosa × hybrida",
      genus: "Rosa",
      family: "Rosaceae",
      kingdom: "Plantae",
      description: "Mawar adalah tanaman bunga yang sangat populer dengan berbagai warna.",
      imageUrl: "/images/rose.jpg",
      careGuide: {
        watering: "Siram 2-3 kali seminggu.",
        sunlight: "Sinar matahari penuh 6-8 jam.",
        temperature: "15-28°C.",
        soil: "Tanah lempung berpasir.",
        fertilizer: "Pupuk khusus mawar setiap 4-6 minggu.",
        humidity: "Kelembaban sedang.",
        toxicity: "Tidak beracun.",
        pruning: "Pangkas di akhir musim dingin.",
        repotting: "Setiap 2 tahun.",
        difficulty: "Sedang",
      },
      distributions: [
        { region: "China", country: "China", latitude: 35.86, longitude: 104.2, type: "native" },
        { region: "Iran", country: "Iran", latitude: 32.43, longitude: 53.69, type: "native" },
        { region: "Prancis", country: "Prancis", latitude: 46.6, longitude: 1.88, type: "native" },
      ],
      diseases: [
        {
          name: "Bercak Hitam",
          scientificName: "Diplocarpon rosae",
          symptoms: "Bercak hitam pada daun.",
          cause: "Jamur.",
          treatment: "Potong daun, semprot fungisida.",
          prevention: "Siram di pangkal.",
        },
      ],
    },
    {
      name: "Anggrek Bulan",
      scientificName: "Phalaenopsis amabilis",
      genus: "Phalaenopsis",
      family: "Orchidaceae",
      kingdom: "Plantae",
      description:
        "Anggrek Bulan adalah anggrek paling populer dengan bunga lebar dan tahan lama.",
      imageUrl: "/images/orchid.jpg",
      careGuide: {
        watering: "Siram 1-2 kali seminggu.",
        sunlight: "Cahaya terang tidak langsung.",
        temperature: "18-30°C.",
        soil: "Media khusus anggrek.",
        fertilizer: "Pupuk anggrek setiap 2 minggu.",
        humidity: "Kelembaban 50-70%.",
        toxicity: "Tidak beracun.",
        pruning: "Potong tangkai bunga layu.",
        repotting: "Setiap 1-2 tahun.",
        difficulty: "Sedang",
      },
      distributions: [
        { region: "Kalimantan", country: "Indonesia", latitude: -1.0, longitude: 114.0, type: "native" },
        { region: "Sulawesi", country: "Indonesia", latitude: -1.91, longitude: 120.81, type: "native" },
        { region: "Filipina", country: "Filipina", latitude: 12.88, longitude: 121.77, type: "native" },
      ],
      diseases: [
        {
          name: "Busuk Hitam",
          scientificName: "Phytophthora cactorum",
          symptoms: "Bercak hitam basah pada daun.",
          cause: "Kelembaban berlebihan.",
          treatment: "Potong terinfeksi, fungisida.",
          prevention: "Jaga sirkulasi udara.",
        },
      ],
    },
    {
      name: "Mangga",
      scientificName: "Mangifera indica",
      genus: "Mangifera",
      family: "Anacardiaceae",
      kingdom: "Plantae",
      description: "Mangga adalah tanaman buah tropis dengan berbagai varietas.",
      imageUrl: "/images/mango.jpg",
      careGuide: {
        watering: "Siram 2-3 kali seminggu.",
        sunlight: "Sinar matahari penuh 8-10 jam.",
        temperature: "24-38°C.",
        soil: "Tanah lempung berpasir.",
        fertilizer: "Pupuk NPK setiap 3 bulan.",
        humidity: "Kelembaban sedang.",
        toxicity: "Buah aman.",
        pruning: "Pangkas setelah panen.",
        repotting: "Untuk pot, setiap 2-3 tahun.",
        difficulty: "Sedang",
      },
      distributions: [
        { region: "India Timur", country: "India", latitude: 22.99, longitude: 87.85, type: "native" },
        { region: "Thailand", country: "Thailand", latitude: 15.87, longitude: 100.99, type: "native" },
        { region: "Indonesia", country: "Indonesia", latitude: -7.26, longitude: 110.0, type: "introduced" },
      ],
      diseases: [
        {
          name: "Antraknosa",
          scientificName: "Colletotrichum gloeosporioides",
          symptoms: "Bercak hitam pada daun dan buah.",
          cause: "Jamur.",
          treatment: "Semprot fungisida tembaga.",
          prevention: "Jaga kebersihan kebun.",
        },
      ],
    },
    {
      name: "Kelapa",
      scientificName: "Cocos nucifera",
      genus: "Cocos",
      family: "Arecaceae",
      kingdom: "Plantae",
      description:
        "Pohon Kelapa adalah tanaman serbaguna yang seluruh bagiannya dapat dimanfaatkan.",
      imageUrl: "/images/coconut.jpg",
      careGuide: {
        watering: "Tanaman muda disiram 2-3 kali seminggu.",
        sunlight: "Sinar matahari penuh 8-10 jam.",
        temperature: "20-35°C.",
        soil: "Tanah berpasir, toleran salin.",
        fertilizer: "Pupuk NPK setiap 4-6 bulan.",
        humidity: "Kelembaban 70-90%.",
        toxicity: "Semua bagian aman.",
        pruning: "Pangkas daun kering.",
        repotting: "Tidak perlu.",
        difficulty: "Mudah",
      },
      distributions: [
        { region: "Indonesia", country: "Indonesia", latitude: -5.0, longitude: 120.0, type: "native" },
        { region: "Filipina", country: "Filipina", latitude: 12.88, longitude: 121.77, type: "native" },
        { region: "India", country: "India", latitude: 14.0, longitude: 77.0, type: "introduced" },
      ],
      diseases: [
        {
          name: "Busuk Tunas",
          scientificName: "Phytophthora palmivora",
          symptoms: "Tunas pusat membusuk.",
          cause: "Jamur.",
          treatment: "Potong terinfeksi, fungisida.",
          prevention: "Jaga kebersihan.",
        },
      ],
    },
    {
      name: "Padi",
      scientificName: "Oryza sativa",
      genus: "Oryza",
      family: "Poaceae",
      kingdom: "Plantae",
      description:
        "Padi adalah tanaman pangan utama di Asia. Biji padi menjadi beras.",
      imageUrl: "/images/rice.jpg",
      careGuide: {
        watering: "Genangan air 5-15 cm.",
        sunlight: "Sinar matahari penuh 8 jam.",
        temperature: "20-35°C.",
        soil: "Tanah liat subur.",
        fertilizer: "Urea 200-300 kg/ha.",
        humidity: "Kelembaban 70-85%.",
        toxicity: "Tidak beracun.",
        pruning: "Tidak perlu.",
        repotting: "Dipanen 100-150 hari.",
        difficulty: "Sedang",
      },
      distributions: [
        { region: "China", country: "China", latitude: 35.86, longitude: 104.2, type: "native" },
        { region: "Indonesia", country: "Indonesia", latitude: -5.0, longitude: 120.0, type: "native" },
        { region: "India", country: "India", latitude: 20.59, longitude: 78.96, type: "native" },
      ],
      diseases: [
        {
          name: "Blast",
          scientificName: "Pyricularia oryzae",
          symptoms: "Bercak coklat pada daun.",
          cause: "Jamur.",
          treatment: "Fungisida sistemik.",
          prevention: "Varietas tahan.",
        },
      ],
    },
    {
      name: "Kembang Sepatu",
      scientificName: "Hibiscus rosa-sinensis",
      genus: "Hibiscus",
      family: "Malvaceae",
      kingdom: "Plantae",
      description: "Kembang Sepatu adalah tanaman hias bunga yang mudah ditemukan di Indonesia.",
      imageUrl: "/images/hibiscus.jpg",
      careGuide: {
        watering: "Siram 2-3 kali seminggu.",
        sunlight: "Sinar matahari penuh 6 jam.",
        temperature: "18-35°C.",
        soil: "Tanah subur, gembur.",
        fertilizer: "Pupuk NPK setiap bulan.",
        humidity: "Kelembaban sedang hingga tinggi.",
        toxicity: "Tidak beracun.",
        pruning: "Pangkas setelah berbunga.",
        repotting: "Setiap 1-2 tahun.",
        difficulty: "Mudah",
      },
      distributions: [
        { region: "China", country: "China", latitude: 35.86, longitude: 104.2, type: "native" },
        { region: "Indonesia", country: "Indonesia", latitude: -5.0, longitude: 120.0, type: "native" },
        { region: "Fiji", country: "Fiji", latitude: -17.71, longitude: 178.07, type: "native" },
      ],
      diseases: [
        {
          name: "Kutu Putih",
          scientificName: "Planococcus citri",
          symptoms: "Bercak putih seperti kapas.",
          cause: "Kutu putih.",
          treatment: "Semprot insektisida.",
          prevention: "Karantina tanaman baru.",
        },
      ],
    },
    {
      name: "Bunga Matahari",
      scientificName: "Helianthus annuus",
      genus: "Helianthus",
      family: "Asteraceae",
      kingdom: "Plantae",
      description:
        "Bunga Matahari terkenal dengan bunganya yang selalu menghadap matahari.",
      imageUrl: "/images/sunflower.jpg",
      careGuide: {
        watering: "Siram 2-3 kali seminggu.",
        sunlight: "Sinar matahari penuh 8 jam.",
        temperature: "21-30°C.",
        soil: "Tanah gembur, subur.",
        fertilizer: "Pupuk NPK setiap 2 minggu.",
        humidity: "Kelembaban sedang.",
        toxicity: "Tidak beracun.",
        pruning: "Pangkas bunga layu.",
        repotting: "Tanaman tahunan.",
        difficulty: "Mudah",
      },
      distributions: [
        { region: "Amerika Serikat", country: "Amerika Serikat", latitude: 37.09, longitude: -95.71, type: "native" },
        { region: "Meksiko", country: "Meksiko", latitude: 23.63, longitude: -102.55, type: "native" },
        { region: "Rusia", country: "Rusia", latitude: 55.76, longitude: 37.62, type: "introduced" },
      ],
      diseases: [
        {
          name: "Jamur Tepung",
          scientificName: "Erysiphe cichoracearum",
          symptoms: "Lapisan putih tepung pada daun.",
          cause: "Kelembaban tinggi.",
          treatment: "Fungisida sulfur.",
          prevention: "Jarak tanam.",
        },
      ],
    },
    {
      name: "Bambu",
      scientificName: "Bambusoideae",
      genus: "Bambusa",
      family: "Poaceae",
      kingdom: "Plantae",
      description: "Bambu adalah tanaman rumput-rumputan dengan batang berkayu.",
      imageUrl: "/images/bamboo.jpg",
      careGuide: {
        watering: "Siram 2-3 kali seminggu.",
        sunlight: "Sinar penuh hingga teduh.",
        temperature: "15-35°C.",
        soil: "Tanah lempung berpasir.",
        fertilizer: "Pupuk NPK setiap 3 bulan.",
        humidity: "Sedang hingga tinggi.",
        toxicity: "Tidak beracun.",
        pruning: "Pangkas batang tua.",
        repotting: "Untuk pot, setiap 2-3 tahun.",
        difficulty: "Mudah",
      },
      distributions: [
        { region: "China", country: "China", latitude: 25.0, longitude: 105.0, type: "native" },
        { region: "Indonesia", country: "Indonesia", latitude: -5.0, longitude: 120.0, type: "native" },
        { region: "India", country: "India", latitude: 20.0, longitude: 78.0, type: "native" },
      ],
      diseases: [
        {
          name: "Jamur Jelaga",
          scientificName: "Capnodium spp.",
          symptoms: "Lapisan hitam pada daun.",
          cause: "Jamur dari serangga.",
          treatment: "Kendalikan serangga.",
          prevention: "Jaga kebersihan.",
        },
      ],
    },
    {
      name: "Pepaya",
      scientificName: "Carica papaya",
      genus: "Carica",
      family: "Caricaceae",
      kingdom: "Plantae",
      description: "Pepaya adalah tanaman buah tropis kaya vitamin C.",
      imageUrl: "/images/papaya.jpg",
      careGuide: {
        watering: "Siram 2-3 kali seminggu.",
        sunlight: "Sinar penuh 8 jam.",
        temperature: "22-35°C.",
        soil: "Tanah gembur, subur.",
        fertilizer: "Pupuk NPK setiap bulan.",
        humidity: "Sedang hingga tinggi.",
        toxicity: "Buah matang aman.",
        pruning: "Pangkas daun kering.",
        repotting: "Berumur 3-5 tahun.",
        difficulty: "Mudah",
      },
      distributions: [
        { region: "Meksiko", country: "Meksiko", latitude: 18.0, longitude: -97.0, type: "native" },
        { region: "Indonesia", country: "Indonesia", latitude: -5.0, longitude: 120.0, type: "introduced" },
        { region: "Brasil", country: "Brasil", latitude: -15.0, longitude: -50.0, type: "introduced" },
      ],
      diseases: [
        {
          name: "Virus Ringspot",
          scientificName: "PRSV",
          symptoms: "Daun menguning, bercak cincin.",
          cause: "Virus dari kutu daun.",
          treatment: "Musnahkan tanaman.",
          prevention: "Bibit tahan virus.",
        },
      ],
    },
    {
      name: "Pisang",
      scientificName: "Musa × paradisiaca",
      genus: "Musa",
      family: "Musaceae",
      kingdom: "Plantae",
      description: "Pisang adalah tanaman buah tropis kaya kalium.",
      imageUrl: "/images/banana.jpg",
      careGuide: {
        watering: "Siram 2-3 kali seminggu.",
        sunlight: "Sinar penuh 8 jam.",
        temperature: "25-35°C.",
        soil: "Tanah gembur, subur.",
        fertilizer: "Pupuk NPK setiap bulan.",
        humidity: "Tinggi 70-90%.",
        toxicity: "Tidak beracun.",
        pruning: "Potong daun kering.",
        repotting: "Perbanyak anakan.",
        difficulty: "Mudah",
      },
      distributions: [
        { region: "Indonesia", country: "Indonesia", latitude: -5.0, longitude: 120.0, type: "native" },
        { region: "Papua Nugini", country: "Papua Nugini", latitude: -6.31, longitude: 143.96, type: "native" },
        { region: "Filipina", country: "Filipina", latitude: 12.88, longitude: 121.77, type: "native" },
      ],
      diseases: [
        {
          name: "Layu Fusarium",
          scientificName: "Fusarium oxysporum",
          symptoms: "Daun menguning, layu.",
          cause: "Jamur tanah.",
          treatment: "Varietas tahan.",
          prevention: "Bibit sehat.",
        },
      ],
    },
    {
      name: "Jeruk",
      scientificName: "Citrus × sinensis",
      genus: "Citrus",
      family: "Rutaceae",
      kingdom: "Plantae",
      description: "Jeruk adalah tanaman buah yang kaya vitamin C.",
      imageUrl: "/images/orange.jpg",
      careGuide: {
        watering: "Siram 2-3 kali seminggu.",
        sunlight: "Sinar penuh 8 jam.",
        temperature: "20-35°C.",
        soil: "Tanah lempung berpasir.",
        fertilizer: "Pupuk NPK setiap 2-3 bulan.",
        humidity: "Sedang hingga tinggi.",
        toxicity: "Buah aman.",
        pruning: "Pangkas cabang mati.",
        repotting: "Untuk pot, 2-3 tahun.",
        difficulty: "Sedang",
      },
      distributions: [
        { region: "China", country: "China", latitude: 25.0, longitude: 110.0, type: "native" },
        { region: "Indonesia", country: "Indonesia", latitude: -5.0, longitude: 120.0, type: "introduced" },
        { region: "Brasil", country: "Brasil", latitude: -15.0, longitude: -50.0, type: "introduced" },
      ],
      diseases: [
        {
          name: "CVPD",
          scientificName: "Liberibacter asiaticus",
          symptoms: "Daun menguning.",
          cause: "Bakteri dari psyllid.",
          treatment: "Musnahkan tanaman.",
          prevention: "Bibit bersertifikat.",
        },
      ],
    },
    {
      name: "Nanas",
      scientificName: "Ananas comosus",
      genus: "Ananas",
      family: "Bromeliaceae",
      kingdom: "Plantae",
      description: "Nanas adalah tanaman buah tropis dengan mahkota daun khas.",
      imageUrl: "/images/pineapple.jpg",
      careGuide: {
        watering: "Siram 2-3 kali seminggu.",
        sunlight: "Sinar penuh 8 jam.",
        temperature: "22-32°C.",
        soil: "Tanah gembur, subur.",
        fertilizer: "Pupuk NPK setiap 2 bulan.",
        humidity: "Sedang hingga tinggi.",
        toxicity: "Buah aman.",
        pruning: "Potong daun kering.",
        repotting: "Perbanyak mahkota buah.",
        difficulty: "Mudah",
      },
      distributions: [
        { region: "Brasil", country: "Brasil", latitude: -20.0, longitude: -55.0, type: "native" },
        { region: "Paraguay", country: "Paraguay", latitude: -25.0, longitude: -57.0, type: "native" },
        { region: "Indonesia", country: "Indonesia", latitude: -5.0, longitude: 120.0, type: "introduced" },
      ],
      diseases: [
        {
          name: "Busuk Akar",
          scientificName: "Phytophthora cinnamomi",
          symptoms: "Daun menguning.",
          cause: "Drainase buruk.",
          treatment: "Kurangi siram.",
          prevention: "Tanah berpasir.",
        },
      ],
    },
    {
      name: "Jahe",
      scientificName: "Zingiber officinale",
      genus: "Zingiber",
      family: "Zingiberaceae",
      kingdom: "Plantae",
      description: "Jahe adalah tanaman rempah yang sangat populer.",
      imageUrl: "/images/ginger.jpg",
      careGuide: {
        watering: "Siram 2-3 kali seminggu.",
        sunlight: "Teduh parsial.",
        temperature: "25-30°C.",
        soil: "Tanah gembur, subur.",
        fertilizer: "Pupuk NPK setiap bulan.",
        humidity: "Tinggi 70-90%.",
        toxicity: "Aman.",
        pruning: "Potong daun kering.",
        repotting: "Panen 8-10 bulan.",
        difficulty: "Mudah",
      },
      distributions: [
        { region: "Indonesia", country: "Indonesia", latitude: -5.0, longitude: 120.0, type: "native" },
        { region: "India", country: "India", latitude: 20.0, longitude: 78.0, type: "native" },
        { region: "China", country: "China", latitude: 25.0, longitude: 110.0, type: "introduced" },
      ],
      diseases: [
        {
          name: "Busuk Rimpang",
          scientificName: "Pythium spp.",
          symptoms: "Rimpang lembek.",
          cause: "Drainase buruk.",
          treatment: "Potong rimpang.",
          prevention: "Bibit sehat.",
        },
      ],
    },
    {
      name: "Kopi",
      scientificName: "Coffea arabica",
      genus: "Coffea",
      family: "Rubiaceae",
      kingdom: "Plantae",
      description: "Kopi adalah tanaman perkebunan penghasil biji kopi.",
      imageUrl: "/images/coffee.jpg",
      careGuide: {
        watering: "Siram 2-3 kali seminggu.",
        sunlight: "Teduh parsial.",
        temperature: "18-25°C.",
        soil: "Tanah vulkanik subur.",
        fertilizer: "Pupuk NPK setiap 3 bulan.",
        humidity: "Tinggi 70-90%.",
        toxicity: "Biji aman diolah.",
        pruning: "Pangkas cabang tidak produktif.",
        repotting: "Untuk pot, 2-3 tahun.",
        difficulty: "Sedang",
      },
      distributions: [
        { region: "Ethiopia", country: "Ethiopia", latitude: 9.0, longitude: 38.0, type: "native" },
        { region: "Indonesia", country: "Indonesia", latitude: -5.0, longitude: 120.0, type: "introduced" },
        { region: "Brasil", country: "Brasil", latitude: -15.0, longitude: -50.0, type: "introduced" },
      ],
      diseases: [
        {
          name: "Karat Daun",
          scientificName: "Hemileia vastatrix",
          symptoms: "Bercak kuning-oranye.",
          cause: "Jamur.",
          treatment: "Fungisida.",
          prevention: "Jaga naungan.",
        },
      ],
    },
    {
      name: "Cabe",
      scientificName: "Capsicum annuum",
      genus: "Capsicum",
      family: "Solanaceae",
      kingdom: "Plantae",
      description: "Cabe adalah tanaman sayuran buah penting dalam masakan Indonesia.",
      imageUrl: "/images/chili.jpg",
      careGuide: {
        watering: "Siram 2-3 kali seminggu.",
        sunlight: "Sinar penuh 8 jam.",
        temperature: "21-30°C.",
        soil: "Tanah gembur, subur.",
        fertilizer: "Pupuk NPK setiap 2 minggu.",
        humidity: "Sedang.",
        toxicity: "Buah aman.",
        pruning: "Pangkas cabang tidak produktif.",
        repotting: "Tanaman semusim.",
        difficulty: "Mudah",
      },
      distributions: [
        { region: "Meksiko", country: "Meksiko", latitude: 20.0, longitude: -98.0, type: "native" },
        { region: "Indonesia", country: "Indonesia", latitude: -5.0, longitude: 120.0, type: "introduced" },
        { region: "India", country: "India", latitude: 20.0, longitude: 78.0, type: "introduced" },
      ],
      diseases: [
        {
          name: "Layu Bakteri",
          scientificName: "Ralstonia solanacearum",
          symptoms: "Layu mendadak.",
          cause: "Bakteri tanah.",
          treatment: "Musnahkan.",
          prevention: "Rotasi tanam.",
        },
        {
          name: "Antraknosa",
          scientificName: "Colletotrichum capsici",
          symptoms: "Bercak hitam pada buah.",
          cause: "Jamur.",
          treatment: "Fungisida tembaga.",
          prevention: "Kebersihan kebun.",
        },
      ],
    },
  ];

  for (const plantData of plants) {
    const { careGuide, distributions, diseases, ...plantInfo } = plantData;
    const plant = await prisma.plant.create({
      data: {
        ...plantInfo,
        careGuide: { create: careGuide },
        distributions: { create: distributions },
        diseases: { create: diseases },
      },
    });
    console.log(`Created plant: ${plant.name}`);
  }
  console.log("Seeding completed!");
}

main()
  .catch((e) => {
    console.error("Error seeding database:", e);
    process.exit(1);
  })
  .finally(() => prisma.$disconnect());
